"""User-facing scientific account of newly executed models."""
import csv
import json

def render(root, table):
    def rows(path):
        with (root/path).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
    vega=rows('data/processed/vega_predictions.csv')
    glab=[r for r in vega if r['compound_id']=='15']
    ve_table=table(glab,[('model_tag','Model'),('assessment','Native assessment'),('applicability_domain_index','ADI'),('source_molecular_weight_warning','Source MW warning')])
    extra=''
    if (root/'data/raw/protox/run_metadata.json').exists():
        extra+='''<h3>ProTox 3.0: official web calculations</h3><p>All six structures were submitted individually for hepatotoxicity, carcinogenicity, mutagenicity and ecotoxicity, in addition to the default oral-toxicity calculation. The API example link returned 404; the official web interface completed the selected runs. Native Active/Inactive calls and their predicted-class confidence are retained. Confidence is not interpreted as a positive-class probability. These endpoints are kept separate from the four-endpoint ADMET-AI/ADMETlab comparison pending definition harmonization.</p><div class="downloads"><a href="data/raw/protox/protox_predictions.csv">Four-endpoint predictions</a><a href="data/raw/protox/oral_predictions.csv">Oral screening</a><a href="data/raw/protox/run_metadata.json">Result URLs and provenance</a></div>'''
    if (root/'results/tables/maplight_heldout_metrics.csv').exists():
        metrics=rows('results/tables/maplight_heldout_metrics.csv')
        for row in metrics:
            for metric in ['roc_auc','average_precision','brier_score']:row[metric]=f"{float(row[metric]):.4f}"
        extra+='''<h3>MapLight: actual model training and held-out evaluation</h3><p>The official MapLight fingerprint/descriptor and CatBoost recipe was trained for AMES, DILI and hERG using five seeds per task. The fixed public TDC train/validation partition was used for fitting; the test partition was used only for evaluation. No stopping or hyperparameter tuning used test labels. This reproduces the published recipe with the recorded current software environment, not an exact leaderboard submission. MapLight+GNN and the remaining endpoints were not run.</p>'''
        extra+=table(metrics,[('task','Task'),('seed','Seed'),('train_n','Train rows'),('test_n','Test rows'),('roc_auc','Test ROC-AUC'),('average_precision','Test AP'),('brier_score','Test Brier score')])
        extra+='''<p>Exact canonical train/test overlaps and project-compound membership are recorded in the run metadata. Correlated public training sets do not provide independent experimental confirmation of GALATEA compounds. Model spread is not a calibrated interval; independent calibration and wet-lab confirmation remain missing.</p><div class="downloads"><a href="data/processed/maplight_predictions.csv">Project ensemble predictions</a><a href="results/tables/maplight_heldout_metrics.csv">Held-out metrics</a><a href="data/raw/maplight/run_metadata.json">Training, split and checkpoint provenance</a><a href="analysis/models/maplight_local.py">Training code</a></div>'''
    extra += '<h3>admetSAR 3.0: six-structure batch completed</h3><p>Official job 175746 returned six records. The unchanged native TXT and normalized table preserve all exported fields. Structures were joined by exact canonical isomeric SMILES. Distinct hERG concentration thresholds and other endpoint definitions remain separate; no cross-platform probabilities are averaged. The batch export contains no domain or uncertainty fields, so these remain unknown.</p><div class="downloads"><a href="data/raw/admetsar/175746_pred.txt">Native batch output</a><a href="data/processed/admetsar_predictions.csv">Structure-matched table</a><a href="data/raw/admetsar/run_metadata.json">Run provenance</a></div>'
    return '''<section class="section" id="executed-models"><div class="kicker">Fresh model execution on Matvision · 28–29 September 2026</div><h2>Predictions, molecular explanations and environmental screening now have run evidence</h2><p>ADMET-AI was recomputed from all ten packaged checkpoints on Matvision: 246 compound–task predictions and 1,230 member outputs. The previous cache is archived. Checkpoint and input hashes, runtime versions and execution logs identify the new run. Counts below describe selected model coverage, not experimental validation or completion of the full sustainability study.</p><div class="downloads"><a href="data/raw/admet_ai/run_metadata.json">Fresh inference metadata</a><a href="docs/methodology/executed_models_20260929.md">Methods and reproduction</a><a href="results/summaries/fresh_execution_manifest.json">Execution provenance</a></div>
<h3>Chemprop: what molecular features contribute to the prediction?</h3><p>Integrated gradients were computed for AMES, skin reaction, DILI and hERG over all six compounds and all five classification members. Both atom and directed-bond features were differentiated; each directed-bond contribution was shared equally between its endpoint atoms. The graph topology remains fixed. Forward predictions match fresh inference within 0.00001, and all 120 numerical completeness checks pass the absolute 0.005 tolerance (maximum residual 0.0047472).</p><figure class="figure"><img src="figures/evidence/chemprop_glabridin_attribution.svg" alt="Glabridin atom contributions for four Chemprop endpoints"><figcaption>PREDICTED. Glabridin (compound 15): red contributions increase and blue contributions decrease the model output relative to the zero-feature baseline. One symmetric color scale spans all four panels. Atom indices match the numerical plot and downloadable table.</figcaption></figure><figure class="figure"><img src="figures/evidence/chemprop_attribution_spread.svg" alt="Mean and standard deviation of atom contributions"><figcaption>Mean ± one standard deviation across five models; uncertainty is model spread, not a confidence interval. A zero-feature graph is a nonphysical baseline. This analysis does not identify causal toxicophores or prove safety; baseline sensitivity remains unresolved.</figcaption></figure><div class="downloads"><a href="results/tables/chemprop_atom_attribution.csv">All atom contributions</a><a href="results/tables/chemprop_attribution_completeness.csv">120 completeness checks</a><a href="data/raw/chemprop/attribution_metadata.json">Method and limits</a><a href="analysis/models/chemprop_attribution.py">Attribution code</a></div>
<h3>VEGA: ten models with native applicability information</h3><p>The official VEGA QSAR 1.2.6 Java bundle executed two human-toxicity, three BCF, one biodegradability, one logP and three aquatic-toxicity models for all six structures (60 compound–model records). Predictions and reliability assessments are preserved. No threshold is invented for a global domain verdict. The table below shows glabridin; all six compounds are downloadable.</p>'''+ve_table+'''<figure class="figure"><img src="figures/evidence/vega_applicability_domain.svg" alt="VEGA native applicability-domain indices"><figcaption>Model-specific ADI values are not probabilities and are not averaged. Twelve records contain source molecular-weight values differing from RDKit by more than 0.5 g/mol; these are flagged and retained unchanged. VEGA outputs preserve constitutional connectivity but do not resolve input stereochemistry.</figcaption></figure><div class="downloads"><a href="data/processed/vega_predictions.csv">60 predictions and source-report paths</a><a href="data/raw/vega/run_metadata.json">Bundle hash and model versions</a><a href="analysis/adapters/GalateaVega.java">Java runner</a></div>
<h3>EPA EPI Suite and ECOSAR: class-specific environmental predictions</h3><p>The EPA-linked EPI Web Suite 1.1.0 batch successfully processed six public SMILES with default settings and no user-supplied property overrides. The unchanged wide export is retained; 54 selected physicochemical/fate values and 118 ECOSAR organism/class/endpoint rows were normalized. Experimental fields in the native file remain separate from selected predicted fields. BIOWIN time-frame scores are not converted into days.</p><figure class="figure"><img src="figures/evidence/ecosar_fish_screening.svg" alt="Class-specific predicted fish acute LC50"><figcaption>PREDICTED. Native classes and mg/L units are kept separately. Crosses mark source warnings or logKow exceedances. Across the full export, 24 rows exceed their model's logKow maximum and 35 carry source flags (these sets can overlap). Absence of these flags is not a complete domain certificate.</figcaption></figure><p>Related BCF/logP methods in VEGA and EPI are not independent votes. No global safety score, measured fate claim or cross-model probability average is produced. EPA CompTox API access remains unavailable without an individual API key.</p><div class="downloads"><a href="data/raw/episuite/episuite_results.csv">Native EPI export</a><a href="data/raw/ecosar/ecosar_aquatic.csv">Native ECOSAR export</a><a href="data/processed/episuite_predictions.csv">Selected EPI properties</a><a href="data/processed/ecosar_predictions.csv">ECOSAR predictions and domain flags</a><a href="data/raw/episuite/run_metadata.json">Web-run provenance</a></div>'''+extra+'</section>'
